# Cloudflare Pages Configuration
name = "studio-ambar"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages specific settings
pages_build_output_dir = "./dist"

[site]
bucket = "./dist"
